<?php

namespace phpdk\tests\unit\util;

use phpdk\lang\TString;
use phpdk\tests\TestCase;
use phpdk\util\AbstractCollection;
use phpdk\tests\mock\TestClassA as A;
use phpdk\tests\mock\EmptyTestClassB as B;

abstract class AbstractCollectionTest extends TestCase
{
    abstract public function buildCollection(...$args) : AbstractCollection;

    public function testInit()
    {
        $collection = $this->buildCollection(A::class);
        static::assertEquals(0, $collection->count());
    }

    public function testAddScalars()
    {
        $collection = $this->buildCollection(TString::class);
        $collection->add(new TString('hello'));
        $collection->add('world');

        static::assertCount(2, $collection);
    }

    public function testInitDefaultCollection()
    {
        $collection = $this->buildCollection();
        static::assertEquals(0, $collection->count());
    }

    public function testAppend()
    {
        $collection = $this->buildCollection(A::class, [
            new A(1),
            new A(2)
        ]);
        static::assertEquals(2, $collection->count());


        $collection2 = $this->buildCollection(A::class);
        $collection2->add(new A(3));
        static::assertEquals(1, $collection2->count());


        $collection3 = $this->buildCollection(A::class);
        $collection3->addAll($collection);
        $collection3->addAll($collection2);
        $collection3->add(new A(5));

        static::assertEquals(4, $collection3->count());


        $collection4 = $this->buildCollection(A::class);
        $collection4->addAll((function () {
             yield new A(1);
             yield new A(2);
             yield new A(3);
        })());

        static::assertCount(3, $collection4);
    }

    public function testAppendFail()
    {
        $collection = $this->buildCollection(A::class, [
            new A(1),
            new A(2)
        ]);
        $this->expectException(\phpdk\lang\Exception::class);
        $collection->add(new B);
        static::assertEquals(2, $collection->count());
    }

    public function testIterator()
    {

        /** @var AbstractCollection $stringCollection */
        $stringCollection = new class extends AbstractCollection
        {
            public function __construct(...$args)
            {
                parent::__construct(TString::class, $args[0] ?? []);
            }

            protected function createObject($model)
            {
                $model = new TString($model);

                return parent::createObject($model); // TODO: Change the autogenerated stub
            }
        };

        $stringCollection->add("Hello");
        $stringCollection->add(" ");
        $stringCollection->add(new TString("World"));

        $str = $stringCollection->toArray()->implode();

        static::assertEquals($str->getValue(), "Hello World");
    }




}
