<?php

use Types\collections\TCollection as Collection;
use Types\collections\CollectionException;
use Types\tests\TestCase;
use Types\TString;

class A
{
    var $i = 0;

    public function __construct($i)
    {
        $this->i = $i;
    }

}

class B
{
}

class CollectionTest extends TestCase
{
    public function testInit()
    {
        $collection = new Collection(A::class);
        static::assertEquals(0, $collection->count());
    }

    public function testInitDefaultCollection()
    {
        $collection = new Collection;
        static::assertEquals(0, $collection->count());
    }

    public function testAppend()
    {
        $collection = new Collection(A::class, [
            new A(1),
            new A(2)
        ]);
        static::assertEquals(2, $collection->count());


        $collection2 = new Collection(A::class);
        $collection2->add(new A(3));
        static::assertEquals(1, $collection2->count());


        $collection3 = new Collection(A::class);
        $collection3->addAll($collection);
        $collection3->addAll($collection2);
        $collection3->add(new A(5));

        static::assertEquals(4, $collection3->count());


        $collection4 = new Collection(A::class);
        $collection4->addAll((function () {
             yield new A(1);
             yield new A(2);
             yield new A(3);
        })());

        static::assertCount(3, $collection4);
    }

    public function testAppendFail()
    {
        $collection = new Collection(A::class, [
            new A(1),
            new A(2)
        ]);
        $this->setExpectedException(CollectionException::class);
        $collection->add(new B);
        static::assertEquals(2, $collection->count());
    }

    public function testIterator()
    {

        /** @var Collection $stringCollection */
        $stringCollection = new class extends Collection
        {
            public function __construct(...$args)
            {
                parent::__construct(TString::class, $args[0] ?? []);
            }

            protected function createObject($model)
            {
                $model = new TString($model);

                return parent::createObject($model); // TODO: Change the autogenerated stub
            }

        };

        $stringCollection->add("Hello");
        $stringCollection->add(" ");
        $stringCollection->add(new TString("World"));


        $str = (string)$stringCollection->toArray()->implode();
        static::assertEquals($str, "Hello World");

    }




}
